"""virtual added

Revision ID: 1d08be3159f0
Revises: 40f81c9bb312
Create Date: 2018-08-27 09:33:09.653177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d08be3159f0'
down_revision = '40f81c9bb312'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('virtual',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('genbank_file', sa.String(length=10000000), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_virtual_name'), 'virtual', ['name'], unique=True)
    op.create_index(op.f('ix_virtual_timestamp'), 'virtual', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_virtual_timestamp'), table_name='virtual')
    op.drop_index(op.f('ix_virtual_name'), table_name='virtual')
    op.drop_table('virtual')
    # ### end Alembic commands ###
