"""new user fields

Revision ID: 40f81c9bb312
Revises: 90f1e17faf0a
Create Date: 2018-08-26 17:20:10.201455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40f81c9bb312'
down_revision = '90f1e17faf0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('bio', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_online', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_online')
    op.drop_column('user', 'bio')
    # ### end Alembic commands ###
